#!/usr/bin/env bash


################################################################################
### Head: Note
##

## * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/project/bin/install.sh

##
### Tail: Note
################################################################################


################################################################################
### Head: Init
##

THE_BASE_DIR_PATH="$(cd -- "$(dirname -- "$0")" ; pwd)"
#THE_PLAN_DIR_PATH="$THE_BASE_DIR_PATH"
#THE_CONFIG_FILE_PATH="${THE_PLAN_DIR_PATH}/demo.conf"
#source "$THE_CONFIG_FILE_PATH"
#. "$THE_CONFIG_FILE_PATH"

##
### Tail: Init
################################################################################


################################################################################
### Head: Util / Debug
##

util_error_echo () {
	echo "$@" 1>&2
}

##
### Head: Util / Debug
################################################################################


################################################################################
### Head: Model / Demo
##

sys_run_demo () {
	util_error_echo "## TODO: sys_run_demo"
	util_error_echo "$PATH"

	#feh --bg-fill ~/Pictures/wall/chad.png &
	feh --bg-fill ~/Pictures/Wallpaper/default.png &

	#xrdb merge ~/Public/xresources/ocean/.Xresources &

	picom &

	#xbacklight -set 10 &

	#~/.dwm/bars/onedark.sh &
	#~/.dwm/bars/fix.sh &

	/lib/openbox/openbox-xdg-autostart

}

mod_run_demo () {
	sys_run_demo
}

##
### Tail: Model / Demo
################################################################################


################################################################################
### Head: Main
##

__main__ () {
	mod_run_demo
}

__main__

##
### Tail: Main
################################################################################
